/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Random;
import javax.swing.table.DefaultTableModel;
import model.bean.Exercicios;
import model.bean.GrupoMuscular;
import model.dao.ExerciciosDAO;
import model.dao.Old_GruposMuscularesDAO;


/**
 *
 * @author yanlf
 */
public class FrameCadastroExercicios extends javax.swing.JFrame {

    /**
     * Creates new form FrameExercicios
     */
    public FrameCadastroExercicios() {
        initComponents();
        ViewComboBox ();
        //readJTable();
        
    }
    
    public void ViewComboBox (){
        
        Old_GruposMuscularesDAO gdao = new Old_GruposMuscularesDAO();
        
        for (GrupoMuscular g: gdao.read()){
            
            ComboGrupoMuscular.addItem(g);
        }
    }
    
    /*public void readJTable (){
        
        DefaultTableModel model = (DefaultTableModel) TableExercicios.getModel();
        
        model.setNumRows(0);
        
        ExerciciosDAO edao = new ExerciciosDAO();
        
        for(Exercicios e:edao.read()){
            
            model.addRow(new Object[]{
                    
                    e.getIdExercicios(),
                    e.getdescExercicio(),
                    e.getIdGruposMusculares()
                    
                    
            });
        }
        
    }
    
    public void readPesquisa (String pesquisa){
        
        DefaultTableModel model = (DefaultTableModel) TableExercicios.getModel();
        
        model.setNumRows(0);
        
        ExerciciosDAO edao = new ExerciciosDAO();
        
        for(Exercicios e:edao.readPesquisaExercicio(pesquisa)){
            
            model.addRow(new Object[]{
                    
                    e.getIdExercicios(),
                    e.getdescExercicio(),
                    e.getIdGruposMusculares()
                    
                    
            });
        }
        
    }
    
    public void readPesquisadescGrupo (String pesquisa){
        
        DefaultTableModel model = (DefaultTableModel) TableExercicios.getModel();
        
        model.setNumRows(0);
        
        ExerciciosDAO edao = new ExerciciosDAO();
        
        for(Exercicios e:edao.readPesquisaDesc(pesquisa)){
            
            model.addRow(new Object[]{
                    
                    e.getIdExercicios(),
                    e.getdescExercicio(),
                    e.getIdGruposMusculares()
                    
                    
            });
        }
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCadastrarExercicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ComboGrupoMuscular = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtExercicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtbCancelar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        labelGeradorID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercicios");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(369, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(369, 200));
        jPanel1.setLayout(null);

        jbCadastrarExercicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbCadastrarExercicio.setText("Cadastrar");
        jbCadastrarExercicio.setToolTipText("Cadastrar Exercicio");
        jbCadastrarExercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastrarExercicio.setMaximumSize(new java.awt.Dimension(100, 30));
        jbCadastrarExercicio.setMinimumSize(new java.awt.Dimension(100, 30));
        jbCadastrarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarExercicioActionPerformed(evt);
            }
        });
        jPanel1.add(jbCadastrarExercicio);
        jbCadastrarExercicio.setBounds(130, 140, 100, 30);
        jbCadastrarExercicio.getAccessibleContext().setAccessibleName("Atualizar ");
        jbCadastrarExercicio.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Exercício");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 60, 30);

        ComboGrupoMuscular.setToolTipText("Grupo Muscular");
        ComboGrupoMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGrupoMuscularActionPerformed(evt);
            }
        });
        jPanel1.add(ComboGrupoMuscular);
        ComboGrupoMuscular.setBounds(110, 90, 230, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar Exercícios");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 229, 32);

        txtExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExercicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtExercicio);
        txtExercicio.setBounds(109, 50, 230, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Grupo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 60, 30);

        jtbCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtbCancelar.setText("Cancelar");
        jtbCancelar.setToolTipText("Cancelar operação");
        jtbCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        jtbCancelar.setMinimumSize(new java.awt.Dimension(100, 30));
        jtbCancelar.setName("JTBCancelar"); // NOI18N
        jtbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jtbCancelar);
        jtbCancelar.setBounds(240, 140, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FUndo.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(369, 200));
        jLabel3.setMinimumSize(new java.awt.Dimension(369, 200));
        jLabel3.setPreferredSize(new java.awt.Dimension(369, 200));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 369, 200);

        labelGeradorID.setForeground(new java.awt.Color(255, 255, 255));
        labelGeradorID.setText("jLabel3");
        jPanel1.add(labelGeradorID);
        labelGeradorID.setBounds(60, 143, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleDescription("Exercicios");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarExercicioActionPerformed
        
        
        Random gerador = new Random();

        //gera id aleatorio
        for (int i = 0; i < 1; i++) {
            labelGeradorID.setText(String.valueOf(gerador.nextInt(5555)));
        }
        
        Exercicios e = new Exercicios();
        ExerciciosDAO edao = new ExerciciosDAO();
        GrupoMuscular g = (GrupoMuscular) ComboGrupoMuscular.getSelectedItem();
        g.getId();
        
        e.setIdExercicios(labelGeradorID.getText());
        e.setdescExercicio(txtExercicio.getText());
        e.setIdGruposMusculares(g);
        
        
        edao.Create(e);
        
        txtExercicio.setText("");
        //readJTable();
    }//GEN-LAST:event_jbCadastrarExercicioActionPerformed

    private void ComboGrupoMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGrupoMuscularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGrupoMuscularActionPerformed

    private void txtExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExercicioActionPerformed

    private void jtbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jtbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroExercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> ComboGrupoMuscular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrarExercicio;
    private javax.swing.JToggleButton jtbCancelar;
    private javax.swing.JLabel labelGeradorID;
    private javax.swing.JTextField txtExercicio;
    // End of variables declaration//GEN-END:variables
}
